spool c:\DocumentsandSetting\Administrateur\bureau

--3a

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL AND SALARY BETWEEN 5000 AND 10000
      AND DEPARTMENT_ID=60; 
  
--3B
SELECT LAST_NAME, JOB_ID, SALARY + 1*(SALARY*0.09)
FROM EMPLOYEES
WHERE SALARY < 4000;
SPOOL OFF;

--3C
ALTER SESSION SET NLS_DATE_FORMAT='MONTH, DD YYYY';

SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE to_char(HIRE_DATE,'mm') = '01';

--4d

SELECT * FROM LOCATIONS
WHERE COUNTRY_ID IN('CA','US');
SPOOL OFF;
